### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by AndreTheGamer** [PocketProjects/PocketPanel#4]
I think we need another logo similar to the PocketStats one?

What do you think?

**Comment by TheKillerTacos** [comment]
Ok, let me make it, just some simple PS and done!

**Comment by TheKillerTacos** [comment]
Darkblue-blue style,

**Comment by AndreTheGamer** [comment]
yep lol

**Comment by SkygridRex** [comment]
nope darkred-orange style

**Comment by SkygridRex** [comment]
@TheKillerTacos add me please

**Comment by AndreTheGamer** [comment]
@SkygridRex  Added!

**Comment by SkygridRex** [comment]
thx

**Comment by SkygridRex** [comment]
index.php it´s broken

**Comment by TheKillerTacos** [comment]
Finished, Closing
