### ISSUE TITLE
[TKRT] Sorry, But Goodbye! (Read this)

### ISSUE THREAD

**Issue by TheKillerTacos** [PocketProjects/PocketPanel#8]
Sorry, its me TheKillerTacos, Im abandoning GitHub, But maintaining the names of:
* TKRT
* TKRT Creations
* TheKillerTacos

and anything with mostly "TKRT" :L

Anyways, I will not delete my GitHub account, im just going to leave it as-is,
just that you might not see me around on months, or years... 

Anyways, you are free to kick me out of any organization, I will not be active in
a long time, sorry, but its time for a change....

- TKRT

**Comment by xZeroMCPE** [comment]
@TheKillerTacos  We"ll miss you :)

Come back anytime!

**Comment by TheKillerTacos** [comment]
ill try, you "Might" see me around...

**Comment by TheKillerTacos** [comment]
Not only on Github ;)

**Comment by xZeroMCPE** [comment]
Okay! :+1:

**Comment by SkygridRex** [comment]
Oh My Herman! I Will miss you.
Oh, God! I was thinking in leave all related-minecraft things.

**Comment by SkygridRex** [comment]
@TheKillerTacos A que se debe tu retiro?

**Comment by TheKillerTacos** [comment]
I am going to be busy doing "other" things, which will lead me to stop making Open Source Things, and also I "might" be around here for small things,
